### ISSUE TITLE
观察自己面板C键的时候，就不要出现装备对比了吧。

### ISSUE THREAD

**Issue by aixiu** [DengSir/tdInspect#7]
![J~714`NG54{H@ 0UKMUAQ%C](https://github.com/user-attachments/assets/2904c378-12f3-4e9c-a19c-cbb67135c2ea)
MerInspect 插件此处就设置的合理点。查看自身列表时，没有对比哦。麻烦了

**Comment by DengSir** [comment]
2.2.7版本

**Comment by aixiu** [comment]
好的，感谢
